### ISSUE TITLE
Check that thing with performance drop

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/noggit3#11]
lots of models in the report so check the changes to the model loading function (why did I not make my own?)

**Comment by ihm-tswow** [comment]
It's neither addM2 nor addWMO, they're both only called from the Object editor

**Comment by ihm-tswow** [comment]
I've gone over the other files and can't find anything that should cause this. Will build a few versions and compare

**Comment by ihm-tswow** [comment]
Could very well be the qt (or opengl) version

**Comment by bloerwald** [comment]
Can you give the context of this issue? I guess it tanks when adding models in scripts?

**Comment by ihm-tswow** [comment]
What I know from the person who reported it:

- Completely unrelated to scripting, just loading a map with "many models" (unsure how many) takes seconds instead of subseconds.

I've asked for further clarifications and if they want to try out the Qt5.9 build to see if that fixes it.

I kind of doubt this has anything to do with the scripting tool itself.

**Comment by ihm-tswow** [comment]
When I sent the Qt5.9 version:
>This version seems to run better

>Also the UI looks better too :smile:

>yeah it definitly runs better tried it a few times

>and the new version gets better loading times for sure

**Comment by bloerwald** [comment]
Sounds like a `close: can't-fix-unknown-issue`? :D

**Comment by ihm-tswow** [comment]
just use 5.9
