### ISSUE TITLE
script errors in global scope of one script comes up when calling "select" in a completely unrelated script

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/noggit3#12]
is this problem fixable?

**Comment by bloerwald** [comment]
How completely unrelated would that be? Is it required to be included somewhere or does daScript just parse absolutely everything in the directory?

**Comment by ihm-tswow** [comment]
It was me being silly and mixing things up, it does parse every file to find the ones with at least one event in them and it does need to execute the global scope to find those functions. I'm not exactly sure what we _should_ do. What we do now will catch the first error it finds (in any file), color the script window red and print the error to the console. 

If we didn't do that and just skipped the erroring files instead, scripters wouldn't really know why their own script wasn't working. I guess the _perfect_ solution would be to first add all files by parsing them manually for those functions or something, check each one, and only show the errors on the file the user actually has open in the script window.

**Comment by ihm-tswow** [comment]
not relevant anymore
