### ISSUE TITLE
Risky API functions

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/noggit3#16]
# File System

`read_directory`: Allows users to scan directories, which might be a little much if it isn't sandboxed (idk about C++ but I wouldn't do that if there weren't a builtin boost function for it something).

The reason I can see that we would want to limit file system access somewhat is that while most people in this scene pass around executables pretty carelessly, I can see that script brushes might have a broad appeal and (false) sense of security that traditional tools generally wouldn't have (much easier to say I've just created an incredible script brush just download and try, a bunch of people do and it's a bomb or whatever).

# Network

I can't see any legitimate use-cases for the network module so I disabled that even in the first release.

**Comment by ihm-tswow** [comment]
Maybe check if program is running as administrator (only really possible under windows, but then again, maybe you'll have to assume a linux user has to take more responsibility with how they run the program) and refuse to run scripts if it does. daScript fucks around with raw pointers anyways so idk if it's really meaningful to actually limit the fs at all.

**Comment by ihm-tswow** [comment]
If we have a program that could create symlinks in noggit directories, why wouldn't they just replace the exe or dlls themselves instead

**Comment by bloerwald** [comment]
way too short summary from discord discussions: 

- network is out of the question
- filesystem makes sense for 
  - allow user data, e.g. the images or noise blobs
  - scripts can improve UX by not just reading a single user given file by parameter but by scanning a directory for files and offering them in an enum
  - reading files is not an issue as there is no way to exfiltrate the data
  - writing files is an issue though.
- we want filesystem access
- the API should be as restrictive as possible, even if we are fine with files and directories being read.
- It is probably a good thing if a script calling write there is a user confirmation that it is okay.
  - The reply may be cached per filename but should of course not be cached by plugin (write nice file first, then write something evil). 
  - an "I don't care about anything" flag for users to toggle on plugins might be good for UX, but is not required in a first step, only if people complain too much.

**Comment by ihm-tswow** [comment]
per-session, or should I write the cache to a file?

**Comment by bloerwald** [comment]
I'd go for per-session for now. I wouldn't want my plugins to write too many files, so having to click "yes, please, I do wanted to save the height map" once per session seems fine. Probably will be different filenames anyway, not always the same.

**Comment by ihm-tswow** [comment]
Makes sense

**Comment by ihm-tswow** [comment]
(if any of you is familiar with with qt signals you're welcome to write this, since it's security related I think there's a risk I'll mess something up)

**Comment by ihm-tswow** [comment]
fixed
