### ISSUE TITLE
Fix number templates (int/float/double/uint) in API functions

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/noggit3#17]
This is **really** annoying. We can't really fix arithmetics, but at least we can allow float function parameters to take ints.

**Comment by ihm-tswow** [comment]
I don't think it's worth it to find a real solution to this while others might want to investigate a better wrapping system altogether.

It's still incredibly annoying to have to mess with floats all the time, my suggestion is to make hackwrappers in the noggit ipp file because it's such a small subset of (key) functions that are affected. Compared to other methods:

**no fix at all**: annoying to scripters (worst)
**hackfix in the sources themselves**: annoying to anyone trying to understand the script modules or write their own (bad)
**hackfix in noggit ipp**: annoying for those trying to edit those specific functions, since there are duplicate definitions. But this is the thing we want to discourage most anyways, so I think this is the best way to go.

**Comment by ihm-tswow** [comment]
hackfix: e4eb26f520f5d5774e885769a9c31449020ea33f

**Comment by bloerwald** [comment]
https://github.com/wowdev/noggit3/issues/79
