### ISSUE TITLE
pen/tablet support broken(?)

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/noggit3#24]
Older version of noggit worked with pen/tablets, but doesn't seem to work with this version anymore. Specifically camera dragging is supposedly broken. I'll grab my tablet later and check this out.

**Comment by ihm-tswow** [comment]
I can reproduce this, does not work in script version but works in https://github.com/wowdev/noggit3/releases/tag/test-2992

I noticed it also does that input delay thing with unsupported applications, so maybe this is a qt version thing?

**Comment by ihm-tswow** [comment]
confirmed qt version thing (that or I'm lacking somethng), it's still broken if I build the version at https://github.com/wowdev/noggit3/releases/tag/test-2992

**Comment by ihm-tswow** [comment]
That release used qt version 5.9, and I'm currently using qt version 5.15

**Comment by ihm-tswow** [comment]
@bloerwald do you use a specific qt package for tablet support? I'll try qt5.9 later but I'm really low on disk space atm lol

**Comment by bloerwald** [comment]
Nope, I am not aware of any requirement on version. 

- 5.9.4 fixes a Wacom bug on macOS 
- 5.10.0 fixes a bug on X11.
- 5.11.0 fixes Apple Pencil support on iOS 
- 5.12.0 fixes **[QTBUG-65199] enterEvent() and leaveEvent() now occur when a hovering drawing tablet stylus enters or leaves a widget.** and **adds event compression on Windows 8+**. I would suspect this is the version that breaks it.
- 5.12.4 fixes a bug on X11.
- 5.13.0 fixes a bug on X11.
- 5.15.0 deprecates `QTabletEvent::device(), hiResGlobalXY()` and fixes a bug on X11.

You may also have fudged up with "bundling" Qt. Like everything, tablets are a plugin, `qt.qpa.input.tablet`. It should be provided by platforms/qwindows.dll or platforms/qdirect2d.dll, but you have those in the zip at least, so I wouldn't assume they are missing.

Qt ships examples you can optionally install, which includes a tablet one. You may want to double check whether that example works with the new Qt version before doing the entire 5.9 hassle.

**Comment by ihm-tswow** [comment]
Could not get anything to work with 5.15, but with 5.9.9 it works. Might binsearch to find a newest working version, but for now I have no issues with 5.9

**Comment by bloerwald** [comment]
https://github.com/wowdev/noggit3/issues/77
