### ISSUE TITLE
throwing too many errors crashes noggit

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/noggit3#28]
it's daScripts error handler: 

https://github.com/GaijinEntertainment/daScript/blob/3ef4b644e466725f5434996f43f7fdacd7553a6e/src/simulate/simulate.cpp#L1174

**Comment by ihm-tswow** [comment]
tried enabling DAS_EXCEPTIONS=1 but that just crashed on startup, and it wouldn't compile before I included stdexcept (am I the only one who can't just include exception?)

**Comment by ihm-tswow** [comment]
workaround: 7c862c477704e20fbd8c9ddd1fda64ffbaf40e86

**Comment by bloerwald** [comment]
> am I the only one who can't just include exception?

Nope, the two are annoying and confuse probably everyone. It doesn't help that most of the time they are included implicitly from somewhere else and you don't notice you're including the wrong one.

The idea is that `exception` has the really basic ones, `exception`, `bad_exception`, `nested_exception` and functions, the terminate handling and the currently-inflight, and `stdexcept` has the actual errors thrown by the STL, i.e. `runtime_error`, `logic_error` and the base classes.

Despite `stdexcept` thus having classes that inherit from `exception`, it isn't specced to include `exception`, so on some platforms it rightfully doesn't (but only some implementation detail where `std::exception` is defined).

**Comment by bloerwald** [comment]
https://github.com/wowdev/noggit3/issues/76
